// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PV__DS_y_RH___Proyecto_Gestor_de_Inventario.Migrations
{
    [DbContext(typeof(SQLServerContextGestionInventarioSJCP))]
    [Migration("20250430044955_NuevaMigracion sin eliminacion en cascada")]
    partial class NuevaMigracionsineliminacionencascada
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PV__DS_y_RH___Proyecto_Gestor_de_Inventario.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Prendas de vestir: camisetas, pantalones, chaquetas…",
                            Nombre = "Ropa"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Alimentos en conserva, envasados y frescos.",
                            Nombre = "Comida"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Bebidas alcohólicas y no alcohólicas.",
                            Nombre = "Bebidas"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Productos de despensa: cereales, lácteos, granos.",
                            Nombre = "Abarrotes"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Collares, anillos, pulseras y accesorios metálicos.",
                            Nombre = "Joyas"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Medicamentos y productos de cuidado de la salud.",
                            Nombre = "Fármacos"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Artículos diversos que no encajan en las categorías anteriores.",
                            Nombre = "Otros"
                        });
                });

            modelBuilder.Entity("PV__DS_y_RH___Proyecto_Gestor_de_Inventario.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("PV__DS_y_RH___Proyecto_Gestor_de_Inventario.Models.DetallePedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Obervacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioOriginal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVendido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallePedido");
                });

            modelBuilder.Entity("PV__DS_y_RH___Proyecto_Gestor_de_Inventario.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("PV__DS_y_RH___Proyecto_Gestor_de_Inventario.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("PV__DS_y_RH___Proyecto_Gestor_de_Inventario.Models.DetallePedido", b =>
                {
                    b.HasOne("PV__DS_y_RH___Proyecto_Gestor_de_Inventario.Models.Pedido", "Pedido")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PV__DS_y_RH___Proyecto_Gestor_de_Inventario.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("PV__DS_y_RH___Proyecto_Gestor_de_Inventario.Models.Pedido", b =>
                {
                    b.HasOne("PV__DS_y_RH___Proyecto_Gestor_de_Inventario.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PV__DS_y_RH___Proyecto_Gestor_de_Inventario.Models.Producto", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("ProductoId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PV__DS_y_RH___Proyecto_Gestor_de_Inventario.Models.Producto", b =>
                {
                    b.HasOne("PV__DS_y_RH___Proyecto_Gestor_de_Inventario.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("PV__DS_y_RH___Proyecto_Gestor_de_Inventario.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("PV__DS_y_RH___Proyecto_Gestor_de_Inventario.Models.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("PV__DS_y_RH___Proyecto_Gestor_de_Inventario.Models.Pedido", b =>
                {
                    b.Navigation("DetallesPedido");
                });

            modelBuilder.Entity("PV__DS_y_RH___Proyecto_Gestor_de_Inventario.Models.Producto", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
